### ISSUE TITLE
Getting error

### ISSUE THREAD

**Issue by nniku121** [f13dev/f13-movie#1]
The movie, show or episode you requested could not be found.

**Comment by f13dev** [comment]
Hello @nniku121,

Firstly apologies for the hugely delayed response!

Much of my programming projects were abandonned early 2017 due to a family emergency.

This project along with many others has now been re-started. This plugin specifically has been completely re-written from the ground up and is in a much better operational condition than it was previously. Over the last few years the OMDB API has evolved a reasonable amount meaning the previous release had grown incompatible with the API.

Should you still require the Movie shortcode on your site, or if it is still installed, I would strongly recommend updating the plugin to version 2.0.1 either via the GitHub repository or the WordPress plugins directory. Please note, one of the alterations to the OMDB API is the requirement of a free API key which can be added via WP-Admin > F13 Admin > Movie (OMDB).

Apologies again for the delay.

Jim
